"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, Eye, Search } from "lucide-react";
import Image from "next/image";

export default function GeneratedIDsPage() {
  const [ids] = useState([
    {
      id: "ID-1001",
      name: "Amit Sharma",
      role: "Student",
      class: "10-B",
      generated: "2024-12-01 10:32 AM",
      image: "/id-front.jpg",
      status: "Active",
    },
    {
      id: "ID-1002",
      name: "Priya Gupta",
      role: "Staff",
      class: "Teacher",
      generated: "2024-12-02 03:15 PM",
      image: "/id-front.jpg",
      status: "Active",
    },
  ]);

  return (
    <div className="flex flex-col gap-6 p-4 md:p-6">

      {/* PAGE HEADER */}
      <div>
        <h2 className="text-3xl font-semibold tracking-tight">Generated IDs</h2>
        <p className="text-muted-foreground text-sm">
          List of all ID cards generated by your organization.
        </p>
      </div>

      {/* SEARCH + FILTER BAR */}
      <div className="flex flex-col md:flex-row gap-3 md:items-center">
        <div className="relative w-full md:max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground h-4 w-4" />
          <Input placeholder="Search by name or ID number..." className="pl-9" />
        </div>
      </div>

      {/* GENERATED ID TABLE */}
      <Card className="shadow-sm border">
        <CardHeader>
          <CardTitle className="text-lg">Generated ID Cards</CardTitle>
          <CardDescription>
            View, manage, and download previously generated ID cards.
          </CardDescription>
        </CardHeader>

        <CardContent className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[80px]">Preview</TableHead>
                <TableHead>ID Number</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>Role</TableHead>
                <TableHead>Class / Dept</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Generated On</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>

            <TableBody>
              {ids.map((item) => (
                <TableRow key={item.id}>
                  {/* ID Thumbnail */}
                  <TableCell>
                    <Image
                      src={item.image}
                      width={60}
                      height={40}
                      alt="ID Preview"
                      className="rounded-md border"
                    />
                  </TableCell>

                  <TableCell className="font-medium">{item.id}</TableCell>
                  <TableCell>{item.name}</TableCell>
                  <TableCell>{item.role}</TableCell>
                  <TableCell>{item.class}</TableCell>

                  <TableCell>
                    <Badge
                      variant={item.status === "Active" ? "default" : "secondary"}
                    >
                      {item.status}
                    </Badge>
                  </TableCell>

                  <TableCell>{item.generated}</TableCell>

                  {/* ACTIONS */}
                  <TableCell className="text-right space-x-2">
                    <Button variant="outline" size="icon">
                      <Eye className="h-4 w-4" />
                    </Button>

                    <Button variant="outline" size="icon">
                      <Download className="h-4 w-4" />
                    </Button>
                  </TableCell>

                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

    </div>
  );
}
